version: "3.8"

services:

    pg:
        build: .
        image: rdfito/pg:13.2
        environment:
            POSTGRES_USER: "${POSTGRES_USER:-postgres}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            DB_NAME: "${DB_NAME}"
            DB_DUMP: "${DB_DUMP:-db.dump}"
        volumes:
            - pg:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: on-failure

volumes:
    pg:
