version: '3.8'

services:

    pg10:
        build: .
        image: rdfito/pg10:1.2
        environment:
            POSTGRES_USER: "${POSTGRES_USER:-postgres}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            DB_NAME: "${DB_NAME}"
            DB_USER_NAME: "${DB_USER_NAME}"
            DB_USER_PASSWORD: "${DB_USER_PASSWORD}"
            DB_DUMP: "${DB_DUMP:-db.dump}"
        volumes:
            - postgresql:/var/lib/postgresql/data
        ports:
            - 5432:5432
        restart: on-failure

    pgadmin:
        image: dpage/pgadmin4:4.21
        environment:
            PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
            PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - 8080:80
        links:
            - pg10:pg10
        depends_on:
            - pg10

volumes:
    postgresql:
    pgadmin:
