version: "3.8"

services:

    mysql:
        image: mariadb:10.3.24
        container_name: mysql
        tty: true
        command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: on-failure

    adminer:
        image: adminer:4.7.7
        container_name: adminer
        environment:
            ADMINER_DESIGN: "${ADMINER_DESIGN:-pepa-linha}"
        ports:
            - "8080:8080"
        links:
            - "mysql:mysql"
        depends_on:
            - mysql

volumes:
    mysql:
