version: "3.8"

services:

    mysql:
        image: mariadb:10.3.27
        container_name: mysql_sa
        tty: true
        command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - mysql_sa:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: on-failure

volumes:
    mysql_sa:
